// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "CppTs_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Cpp_window
SEXP Cpp_window(TimeSerie const& x, double tseps, NumericVector const& start, NumericVector const& end);
RcppExport SEXP _CppTs_Cpp_window(SEXP xSEXP, SEXP tsepsSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< TimeSerie const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tseps(tsepsSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type start(startSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpp_window(x, tseps, start, end));
    return rcpp_result_gen;
END_RCPP
}
// test
TimeSerie test(const TimeSerieNumericMatrix& x);
RcppExport SEXP _CppTs_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const TimeSerieNumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(test(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CppTs_Cpp_window", (DL_FUNC) &_CppTs_Cpp_window, 4},
    {"_CppTs_test", (DL_FUNC) &_CppTs_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CppTs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
