# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_window <- function(x, tseps, start, end) {
    .Call('_CppTs_Cpp_window', PACKAGE = 'CppTs', x, tseps, start, end)
}

test <- function(x) {
    .Call('_CppTs_test', PACKAGE = 'CppTs', x)
}

